### ISSUE TITLE
relax pinned version of pydantic

### ISSUE THREAD

**Issue by rdenham** [getodk/pyodk#94]
#### Software and hardware versions 
pyodk v1.0.0, Python 3.12

#### Problem description

Pinning pydantic to 2.6.4 causes a conflict for me. For a project I need pyodk and an internal package that  depends on pydantic-settings >= 2.4.0, but this causes the following error:

```python
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pydantic-settings 2.4.0 requires pydantic>=2.7.0, but you have pydantic 2.6.4 which is incompatible.
```

#### Steps to reproduce the problem

```sh
pip install pydantic-settings==2.4.0
pip install pyodk
```

#### Expected behavior

No dependency conflict.

#### Other information 

I checked by changing the pyproject.toml file so that it has 

```python
dependencies = [
    "requests==2.31.0",  # HTTP with Central
    "toml==0.10.2",      # Configuration files
    "pydantic>=2.6.4",   # Data validation
]
```

and ran the tests, everything seems to pass.

Would the authors consider relaxing he strict pinning on pydantic in `pyproject.toml` file?

**Comment by lindsay-stevens** [comment]
Welcome! Please use the links in the "create new issue" page to get support via the ODK forum, rather than opening a GitHub ticket directly.

The dependency resolver error from pip doesn't prevent pip from installing conflicting versions, it's just letting you know that it detected a potential issue based on the package specifications. It's possible that everything works as expected. A workaround is to install the package with the older dependency first. E.g. using current master branch of the repo and a fresh venv, I get a similar pip error but the desired packages are there:

```
pip install -e .
pip install pydantic-settings==2.4.0
```
Output from `pip list`:
```
Package            Version   Editable project location
------------------ --------- ---------------------------------
annotated-types    0.7.0
certifi            2024.8.30
charset-normalizer 3.3.2
idna               3.8
pip                24.0
pydantic           2.8.2
pydantic_core      2.20.1
pydantic-settings  2.4.0
pyodk              1.0.0     C:\Users\lindsay\repos\pyodk\repo
python-dotenv      1.0.1
requests           2.31.0
toml               0.10.2
typing_extensions  4.12.2
urllib3            2.2.2
```
